### ISSUE TITLE
OVM not getting enabled using `@eth-optimism/plugins/hardhat/web3`

### ISSUE THREAD

**Issue by Amxx** [ethereum-optimism/plugins#26]
[The web3 module for hardhat](https://github.com/ethereum-optimism/plugins/blob/b101b5e8c0e0a6ab88399636b9fdd0c1e7707898/src/hardhat/web3/index.ts#L9) checks that hre.ovm is set. This test fails, which prevents ovm so enable correctly.

This is particularly strange since this value is not used anywhere else in the script. Also, I can find no similar thing on the ethers module.

Is this module old/deprecated? Would it be possible to update it so we can enjoy all the amazing features of optimism with our truffle test suite?

**Comment by tynes** [comment]
Did you try setting `ovm: true` in your hardhat config? These plugins are not currently being prioritized and PRs for bugfixes would be greatly appreciated

**Comment by Amxx** [comment]
I do not have `ovm: true` in my hardhar config. I'll try adding it. But again, this is not necessary when using ethers :/

**Comment by Amxx** [comment]
Note: removing `!hre.ovm` works fine

**Comment by smartcontracts** [comment]
@Amxx this is my fault. We originally made this plugin for Synthetix (they set this variable in their config). I'll make a PR to fix this issue. Sorry about that!

**Comment by smartcontracts** [comment]
Need to figure out how to attach a new flag to `hardhat test` (e.g., `hardhat test --ovm`)

**Comment by Amxx** [comment]
I personally set parameters through ENVVAR, and read these in hardhat.config.js.
Not sure about command line args

**Comment by smartcontracts** [comment]
We're moving away from using web3 like this. You should now just be able to import the compiler plugin and then add the `ovm: true` field to your network config. See tutorial for more information: https://github.com/ethereum-optimism/optimism-tutorial

Closing! Feel free to reopen if you find yourself still having issues with web3 + hardhat.
