### ISSUE TITLE
Importing `@eth-optimism/plugins/hardhat/ethers` breaks source map support

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-optimism/plugins#29]
**Describe the bug**
`import '@eth-optimism/plugins/hardhat/ethers'` 
breaks source map supports (line numbers are off).

This is because importing `ganache-core` which imports `source-map-support/register`.

A related issue in hardhat/waffle: https://github.com/EthWorks/Waffle/issues/281

**Quick workaround**: (for end-users of this lib)
`source-map-support` is able to ąvoid re-registering if one particular version is registered multiple times so a reasonable workaround is to force install only one particular version. To do this add in `package.json`:

```
"resolutions": {
    "source-map-support": "0.5.19"
  }
```

**Solution**:

1. Help me with: https://github.com/trufflesuite/ganache-core/issues/879

**Comment by smartcontracts** [comment]
Glad that https://github.com/trufflesuite/ganache-core/issues/879 seems to be getting resolved. We're likely going to remove all ethereumjs-vm functionality from this repository and prefer using geth directly, which should fix the issue if not immediately fixed in `ganache-core`.

**Comment by gakonst** [comment]
This is the PR which removes ethereumjs-vm: https://github.com/ethereum-optimism/plugins/pull/31

**Comment by smartcontracts** [comment]
Closing this since we no longer use `ethereumjs-vm` under the hood (at least for now). Let me know if you need any other help!!
