### ISSUE TITLE
Plugins/Ganache: Unable to run normal truffle tests that work in truffle

### ISSUE THREAD

**Issue by bghughes** [ethereum-optimism/plugins#8]
While attempting to run `truffle test` in the OVM environment (where I can successfully compile and migrate in the OVM to ganache) with both the @eth-optimism/plugins/ganache and @eth-optimism/ovm-toolchain versions of { ganache } - all normal tests fail with similar errors:

`Error: while migrating WETH9: WETH9 has no network id set, cannot lookup artifact data. Either set the network manually using WETH9.setNetwork(), run WETH9.detectNetwork(), or use new(), at() or deployed() as a thenable which will detect the network automatically.`

For steps to reproduce, feel free to clone my protocol's repository ( https://github.com/RubiconDeFi/rubicon_protocol ) and run `cd ovm && truffle test` after launching ganache with the parameters described in a comment within the ovm/truffle-config.js file. Please let me know if I can provide more details. I would love for this plugin to be "plug and play" with my native truffle tests. Apolgies if I am missing something here....

Also note, while running tests, @eth-optimism/plugins/ganache version of ganache has a lot of logs that run during `truffle test`:
 
`...
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
we creating VM now??
we creating VM now??
...`

**Comment by kfichter** [comment]
> ... got normal provider we wrapping now?? getting normal provider got normal provider we wrapping now?? getting normal provider got normal provider we wrapping now?? getting normal provider got normal provider we wrapping now?? we creating VM now?? we creating VM now?? ...

Hah. Whoops! Okay, I'll try to get a fix for this tonight.

**Comment by smartcontracts** [comment]
Since we've moved away from using `ethereumjs-vm` I'm going to close this issue. New preferred testing method is to run a version of optimistic ethereum locally. Sorry for the delayed response here.
